### ISSUE TITLE
Constellation duplicates

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest-tests-fediverse#83]
in `constellations/saas`. Do we need both?

**Comment by steve-bate** [comment]
Any duplicates are not intentional. 

Looking at some of the other constellations, I see multiple Mastodon-based servers. However, these are for different versions of Mastodon. For example,

| Server | Software | Version |
|--------|----------|---------|
| framapiaf.org | mastodon | 4.2.8 |
| mastodon.social | mastodon | 4.3.0-nightly.2024-05-17 |

**Comment by steve-bate** [comment]
Strangely, `friendi.ca` is reporting a WordPress implementation. Nodeinfo:

```json
{
  "version": "2.0",
  "software": {
    "name": "wordpress",
    "version": "6.5"
  },
  ...
  "protocols": [
    "activitypub"
  ],
  "metadata": {
    "nodeName": "friendica",
    "nodeDescription": "A Decentralized Social Network",
    "nodeIcon": "https://friendi.ca/wp-content/uploads/2016/09/cropped-friendica-1600-1.png"
  }
}
```
The `fediblogs.wordpress.com` server is using WordPress 6.6.

**Comment by jernst** [comment]
I think we are done with this one.
